spring:
  application:
    name: dubbo-demo-provider

dubbo:
  scan:
    base-packages: com.example.dubbo.demo.provider.service.impl
  application:
    name: dubbo-demo-provider
  registry:
    address: "nacos://localhost:8848?username=nacos&password=nacos"
    check: false
  protocol:
    name: dubbo
    port: 20880

logging:
  level:
    com.example.dubbo.demo: DEBUG
