spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: host.docker.internal:8848
        username: nacos
        password: nacos
server:
  port: 8082
