spring:
  application:
    name: dubbo-demo-provider

dubbo:
  application:
    name: dubbo-demo-provider
  registry:
#    address: "nacos://192.168.3.100:8848?username=nacos&password=nacos"
    address: "zookeeper://192.168.3.100:2181"
    check: false
  protocol:
    name: dubbo
    port: 20880
