server.port=8401

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

spring.main.lazy-initialization=true

app.instance-id=${random.uuid}
app.redisson.lock-watchdog-timeout-ms=30000

logging.level.root=INFO
logging.level.com.example.redissonlocklab=INFO
