spring:
  application:
    name: risk-data-hub-lab
  datasource:
    url: jdbc:mysql://192.168.3.100:3306/risk_hub?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 1
      pool-name: HikariPool-risk_hub
  jackson:
    time-zone: Asia/Shanghai
  rabbitmq:
    host: 192.168.3.100
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  data:
    redis:
      host: 192.168.3.100
      port: 6379
      password: 123456

server:
  port: 8501

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: input

hub:
  datasource:
    items:
      - key: trade_oms
        name: 交易系统A库
        datasource-type: TRADE_OMS
        url: jdbc:mysql://192.168.3.100:3306/trade_oms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: 123456
        max-pool-size: 8
        min-idle: 1
      - key: trade_broker
        name: 交易系统B库
        datasource-type: TRADE_BROKER
        url: jdbc:mysql://192.168.3.100:3306/trade_broker?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: 123456
        max-pool-size: 8
        min-idle: 1


