server:
  port: 12002

eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        - http://peer1:12001/eureka/
        - http://peer3:12003/eureka/
