spring:
  application:
    name: rabbitmq-0601
  rabbitmq:
    addresses: host.docker.internal:5672,host.docker.internal:5673,host.docker.internal:5674
    username: admin
    password: admin123
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10

server:
  port: 8080

logging:
  level:
    com.example.rabbitmq0601: DEBUG
