spring:
  application:
    name: rabbitmq-0601
  rabbitmq:
    addresses: 192.168.3.100:5672,192.168.3.100:5673,192.168.3.100:5674
    username: admin
    password: admin123
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10

server:
  port: 8080

logging:
  level:
    com.example.rabbitmq0601: DEBUG
