version: '3.8'

services:
  rabbit1:
    image: rabbitmq:3-management
    container_name: rabbit1
    hostname: rabbit1
    environment:
      - RABBITMQ_ERLANG_COOKIE=HELL_MODE_COOKIE
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_net

  rabbit2:
    image: rabbitmq:3-management
    container_name: rabbit2
    hostname: rabbit2
    environment:
      - RABBITMQ_ERLANG_COOKIE=HELL_MODE_COOKIE
    networks:
      - rabbitmq_net
    depends_on:
      - rabbit1

  rabbit3:
    image: rabbitmq:3-management
    container_name: rabbit3
    hostname: rabbit3
    environment:
      - RABBITMQ_ERLANG_COOKIE=HELL_MODE_COOKIE
    networks:
      - rabbitmq_net
    depends_on:
      - rabbit1

networks:
  rabbitmq_net:
    driver: bridge
